version: '3'
services:
  db:
    image: postgres:12.2-alpine
    container_name: timehammer-db
    environment:
      POSTGRES_USER: timehammer
      POSTGRES_DB: timehammer
      POSTGRES_PASSWORD: ${TIMEHAMMER_DB_PASSWORD}
      TZ: Etc/UTC
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - timehammer
    restart: unless-stopped
  reverseproxy:
    image: linuxserver/letsencrypt:1.3.0-ls109
    container_name: timehammer-reverseproxy
    environment:
      PUID: 1001 # timehammer
      PGID: 1001 # timehammer
      TZ: Etc/UTC
      URL: kronostools.com
      SUBDOMAINS: timehammer,
      VALIDATION: http
      EMAIL: admin@kronostools.com
      DHLEVEL: 2048
      ONLY_SUBDOMAINS: "true"
      STAGING: "false"
    volumes:
      - ./wksp/reverseproxy/config:/config
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    networks:
      - timehammer
    restart: unless-stopped
  zookeeper:
    image: strimzi/kafka:0.17.0-kafka-2.4.0
    container_name: timehammer-zookeeperkafka
    command: ["sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"]
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - timehammer
    restart: unless-stopped
  kafka:
    image: strimzi/kafka:0.17.0-kafka-2.4.0
    container_name: timehammer-kafka
    command: ["sh", "-c", "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"]
    depends_on:
      - zookeeper
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - timehammer
    restart: unless-stopped
  scheduler:
    build:
      context: ./wksp/timehammer/scheduler
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: timehammer/scheduler:1.0.0
    container_name: timehammer-scheduler
    command: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=remotedemo"]
    depends_on:
      - kafka
    networks:
      - timehammer
    restart: unless-stopped
  catalog:
    build:
      context: ./wksp/timehammer/catalog
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: timehammer/catalog:1.0.0
    container_name: timehammer-catalog
    command: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=remotedemo"]
    environment:
      TIMEHAMMER_DB_PASSWORD: ${TIMEHAMMER_DB_PASSWORD}
    depends_on:
      - db
      - kafka
    networks:
      - timehammer
    restart: unless-stopped
  integration:
    build:
      context: ./wksp/timehammer/integration
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: timehammer/integration:1.0.0
    container_name: timehammer-integration
    command: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=remotedemo"]
    depends_on:
      - kafka
    networks:
      - timehammer
    restart: unless-stopped
  commandprocessor:
    build:
      context: ./wksp/timehammer/commandprocessor
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: timehammer/commandprocessor:1.0.0
    container_name: timehammer-commandprocessor
    command: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=remotedemo"]
    depends_on:
      - kafka
    networks:
      - timehammer
    restart: unless-stopped
  web:
    build:
      context: ./wksp/timehammer/web
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: timehammer/web:1.0.0
    container_name: timehammer-web
    command: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=remotedemo"]
    ports:
      - 8090:8080
    depends_on:
      - kafka
    networks:
      - timehammer
    restart: unless-stopped
  statemachine:
    build:
      context: ./wksp/timehammer/statemachine
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: timehammer/statemachine:1.0.0
    container_name: timehammer-statemachine
    volumes:
      - statemachinedata:/data
    command: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=remotedemo"]
    ports:
      - 8090:8080
    depends_on:
      - kafka
    networks:
      - timehammer
    restart: unless-stopped

volumes:
  dbdata:
  comunytekdata:
  statemachinedata:

networks:
  timehammer: