version: '2.4'
services:
  scheduler:
    build:
      context: ./wksp/timehammer/scheduler
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-scheduler-native:1.0.0-SNAPSHOT
  catalog:
    build:
      context: ./wksp/timehammer/catalog
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-catalog-native:1.0.0-SNAPSHOT
  core:
    build:
      context: ./wksp/timehammer/core
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-core-native:1.0.0-SNAPSHOT
  integration:
    build:
      context: ./wksp/timehammer/integration
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-integration-native:1.0.0-SNAPSHOT
  comunytek:
    build:
      context: ./wksp/timehammer/comunytek
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-comunytek-native:1.0.0-SNAPSHOT
  commandprocessor:
    build:
      context: ./wksp/timehammer/commandprocessor
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-commandprocessor-native:1.0.0-SNAPSHOT
  telegramchatbot:
    build:
      context: ./wksp/timehammer/telegramchatbot
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-telegramchatbot-native:1.0.0-SNAPSHOT
  telegramchatbotnotifier:
    build:
      context: ./wksp/timehammer/telegramchatbotnotifier
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-telegramchatbotnotifier-native:1.0.0-SNAPSHOT
  web:
    build:
      context: ./wksp/timehammer/web
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-web-native:1.0.0-SNAPSHOT
  statemachine:
    build:
      context: ./wksp/timehammer/statemachine
      dockerfile: ./src/main/docker/Dockerfile.native.tiny
    image: qopuir/timehammer-statemachine-native:1.0.0-SNAPSHOT