version: '3'
services:
  common:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
  monolith:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 9010:8080
      - 6000:5005
  scheduler:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6010:5005
  catalog:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6020:5005
  core:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6030:5005
  integration:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6040:5005
  comunytek:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6050:5005
  commandprocessor:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6060:5005
  telegramchatbot:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6070:5005
  telegramchatbotnotifier:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6080:5005
  web:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 9000:8080
      - 6090:5005
  statemachine:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6100:5005