version: '3'
services:
  monolithnativebuild:
    image: quay.io/quarkus/centos-quarkus-maven:20.0.0-java8
    container_name: timehammer-monolithnativebuild
    volumes:
      - ./wksp/timehammer:/project/timehammer
    working_dir: /project/timehammer
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    networks:
      - timehammer
  monolithnative:
    build:
      context: ./wksp/timehammer
      dockerfile: ./monolith/src/main/docker/Dockerfile.native.tiny
    image: timehammer-native:1.0.0
    container_name: timehammernative
    ports:
      - 9000:8080
    networks:
      - timehammer