version: '2.4'
services:
  scheduler:
    build:
      context: ./wksp/timehammer/scheduler
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-scheduler:1.0.0-SNAPSHOT
  catalog:
    build:
      context: ./wksp/timehammer/catalog
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-catalog:1.0.0-SNAPSHOT
  core:
    build:
      context: ./wksp/timehammer/core
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-core:1.0.0-SNAPSHOT
  integration:
    build:
      context: ./wksp/timehammer/integration
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-integration:1.0.0-SNAPSHOT
  comunytek:
    build:
      context: ./wksp/timehammer/comunytek
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-comunytek:1.0.0-SNAPSHOT
  commandprocessor:
    build:
      context: ./wksp/timehammer/commandprocessor
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-commandprocessor:1.0.0-SNAPSHOT
  telegramchatbot:
    build:
      context: ./wksp/timehammer/telegramchatbot
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-telegramchatbot:1.0.0-SNAPSHOT
  telegramchatbotnotifier:
    build:
      context: ./wksp/timehammer/telegramchatbotnotifier
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-telegramchatbotnotifier:1.0.0-SNAPSHOT
  web:
    build:
      context: ./wksp/timehammer/web
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-web:1.0.0-SNAPSHOT
  statemachine:
    build:
      context: ./wksp/timehammer/statemachine
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: qopuir/timehammer-statemachine:1.0.0-SNAPSHOT