version: '3'
services:
  db:
    image: postgres:12.2-alpine
    container_name: timehammer-db
    environment:
      POSTGRES_USER: timehammer
      POSTGRES_DB: timehammer
      POSTGRES_PASSWORD: ${TIMEHAMMER_DB_PASSWORD}
      TZ: Etc/UTC
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - timehammer
    restart: unless-stopped
  reverseproxy:
    image: linuxserver/letsencrypt:1.3.0-ls109
    container_name: timehammer-reverseproxy
    environment:
      PUID: 1001 # timehammer
      PGID: 1001 # timehammer
      TZ: Etc/UTC
      URL: kronostools.com
      SUBDOMAINS: timehammer,
      VALIDATION: http
      EMAIL: admin@kronostools.com
      DHLEVEL: 2048
      ONLY_SUBDOMAINS: "true"
      STAGING: "false"
    volumes:
      - ./wksp/reverseproxy/config:/config
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    networks:
      - timehammer
    restart: unless-stopped
  timehammercore:
    image: maven:3.6.3-jdk-11-slim
    container_name: timehammer-core
    env_file:
      - .env
    volumes:
      - ./wksp/timehammer:/root/wksp/timehammer
      - ${HOME}/.m2/repository:/root/.m2/repository
    working_dir: /root/wksp/timehammer/timehammer-core
    command: mvn -Dquarkus.profile=remotedemo quarkus:dev
    networks:
      - timehammer
    restart: unless-stopped

volumes:
  dbdata:

networks:
  timehammer: