version: '3'
services:
  common:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
  monolith:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 9000:8080
      - 6000:5005
  scheduler:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6010:5005
  core:
    volumes:
      - ${USERPROFILE}/.m2/repository:/root/.m2/repository
    command: ["mvn", "-Dquarkus.profile=localdemo", "quarkus:dev"]
    ports:
      - 6020:5005