mp:
  messaging:
    incoming:
      holidays-worker-summary:
        connector: smallrye-kafka
        topic: holidays-worker-summary
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidayWorkerJacksonDeserializer
    outgoing:
      schedule-update-holidays:
        connector: smallrye-kafka
        topic: schedule-update-holidays
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      schedule-summary:
        connector: smallrye-kafka
        topic: schedule-summary
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

timehammer:
  schedules:
    # cron expressions (https://www.freeformatter.com/cron-expression-generator-quartz.html)
    update-workers-status:
      name: updateWorkersStatus
      enabled: true
      ## Update workers' status -> every 2 minutes starting at minute 0, every hour between 05am and 19pm, every day between Monday and Friday, every month
      cron: 0 0/2 5-19 ? * MON-FRI *
    clean-past-workers-holidays:
      name: cleanPastWorkersHolidays
      enabled: true
      ## Remove workers' past holidays -> At 03:00:00am UTC, on the 1st day, in January
      cron: 0 0 3 1 JAN ? *
    update-workers-holidays:
      name: updateWorkersHolidays
      enabled: true
      ## Update workers' holidays -> At 03:10:00am UTC, every day between Monday and Friday, every month
      cron: 0 10 3 ? * MON-FRI *
    clean-ssid-tracking-events:
      name: cleanSsidTrackingEvents
      enabled: true
      ## Clean SSID tracking events -> At 03:20:00am UTC, every day between Monday and Friday, every month
      cron: 0 20 3 ? * MON-FRI *
    clean-trash-messages:
      name: cleanTrashMessages
      enabled: true
      ## Clean Trash Messages -> At 03:30:00am UTC, every day between Monday and Friday, every month
      cron: 0 30 3 ? * MON-FRI *

"%localdemo":
  timehammer:
    schedules:
      update-workers-holidays:
        enabled: false