quarkus:
  camel:
    main:
      routes-discovery:
        enabled: false

mp:
  messaging:
    incoming:
      notification-telegram:
        connector: smallrye-kafka
        topic: notification-telegram
        value:
          deserializer: com.kronostools.timehammer.common.messages.telegramchatbot.deserializers.TelegramChatbotNotificationMessageJacksonDeserializer

camel:
  context:
    name: timehammer-camel-cdi

timehammer:
  mocks:
    notificationservice: false
  chatbot:
    token: ${TIMEHAMMER_CHATBOT_TOKEN}

"%localdemo":
  timehammer:
    mocks:
      notificationservice: true
    chatbot:
      token: ${TIMEHAMMER_CHATBOT_TOKEN_DEMO}

"%remotedemo":
  timehammer:
    mocks:
      notificationservice: true
    chatbot:
      token: ${TIMEHAMMER_CHATBOT_TOKEN_DEMO}