quarkus:
  camel:
    routes-discovery:
      enabled: false

mp:
  messaging:
    outgoing:
      command-preprocess:
        connector: smallrye-kafka
        topic: command-preprocess
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      answer-id:
        connector: smallrye-kafka
        topic: answer-id
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

camel:
  context:
    name: timehammer-camel-cdi

timehammer:
  chatbot:
    token: ${TIMEHAMMER_CHATBOT_TOKEN}

"%localdemo":
  timehammer:
    chatbot:
      token: ${TIMEHAMMER_CHATBOT_TOKEN_DEMO}

"%remotedemo":
  timehammer:
    chatbot:
      token: ${TIMEHAMMER_CHATBOT_TOKEN_DEMO}