mp:
  messaging:
    incoming:
      comunytek-worker-holidays:
        connector: smallrye-kafka
        topic: comunytek-worker-holidays
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidayWorkerJacksonDeserializer
      comunytek-worker-register:
        connector: smallrye-kafka
        topic: comunytek-worker-register
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
      comunytek-worker-update-password:
        connector: smallrye-kafka
        topic: comunytek-worker-update-password
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerUpdatePasswordRequestJacksonDeserializer
      comunytek-worker-status:
        connector: smallrye-kafka
        topic: comunytek-worker-status
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.CheckWorkersStatusWorkerJacksonDeserializer
    outgoing:
      holidays-worker-update:
        connector: smallrye-kafka
        topic: holidays-worker-update
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-register-persist:
        connector: smallrye-kafka
        topic: worker-register-persist
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      status-worker-process:
        connector: smallrye-kafka
        topic: status-worker-process
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-update-password-notify:
        connector: smallrye-kafka
        topic: worker-update-password-notify
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

timehammer:
  comunytek:
    login-cache:
      expiration:
        qty: 9
        unit: MINUTES