quarkus:
  datasource:
    db-kind: postgresql
    username: timehammer
    password: ${TIMEHAMMER_DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://db:5432/timehammer
    reactive:
      url: postgresql://db:5432/timehammer

  flyway:
    migrate-at-start: true

mp:
  messaging:
    incoming:
      schedule-update-holidays:
        connector: smallrye-kafka
        topic: schedule-update-holidays
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.ScheduleTriggerMessageJacksonDeserializer
      schedule-clean-holidays:
        connector: smallrye-kafka
        topic: schedule-clean-holidays
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.ScheduleTriggerMessageJacksonDeserializer
      holidays-worker-update:
        connector: smallrye-kafka
        topic: holidays-worker-update
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidayWorkerJacksonDeserializer
      command-preprocess:
        connector: smallrye-kafka
        topic: command-preprocess
        value:
          deserializer: com.kronostools.timehammer.common.messages.telegramchatbot.deserializers.TelegramChatbotInputMessageJacksonDeserializer
      command-id-in:
        connector: smallrye-kafka
        topic: command-id
        value:
          deserializer: com.kronostools.timehammer.common.messages.telegramchatbot.deserializers.TelegramChatbotInputMessageJacksonDeserializer
      worker-register-validate:
        connector: smallrye-kafka
        topic: worker-register-validate
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
      worker-register-persist-in:
        connector: smallrye-kafka
        topic: worker-register-persist
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
    outgoing:
      holidays-worker-get:
        connector: smallrye-kafka
        topic: holidays-worker-get
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-worker-summary:
        connector: smallrye-kafka
        topic: holidays-worker-summary
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-clean-summary:
        connector: smallrye-kafka
        topic: holidays-clean-summary
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      command-id-out:
        connector: smallrye-kafka
        topic: command-id
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      command-process:
        connector: smallrye-kafka
        topic: command-process
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-register-persist-out:
        connector: smallrye-kafka
        topic: worker-register-persist
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-register-notify-out:
        connector: smallrye-kafka
        topic: worker-register-notify
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer