quarkus:
  datasource:
    db-kind: postgresql
    username: timehammer
    password: ${TIMEHAMMER_DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://db:5432/timehammer
    reactive:
      url: postgresql://db:5432/timehammer

  flyway:
    migrate-at-start: true

mp:
  messaging:
    incoming:
      schedule-update-holidays:
        connector: smallrye-kafka
        topic: schedule-update-holidays
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.ScheduleTriggerMessageJacksonDeserializer
      schedule-clean-holidays:
        connector: smallrye-kafka
        topic: schedule-clean-holidays
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.ScheduleTriggerMessageJacksonDeserializer
      holidays-worker-update:
        connector: smallrye-kafka
        topic: holidays-worker-update
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidayWorkerJacksonDeserializer
    outgoing:
      holidays-worker-auth:
        connector: smallrye-kafka
        topic: holidays-worker-auth
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-worker-summary:
        connector: smallrye-kafka
        topic: holidays-worker-summary
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-clean-summary:
        connector: smallrye-kafka
        topic: holidays-clean-summary
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer