mp:
  messaging:
    incoming:
      holidays-worker-get:
        connector: smallrye-kafka
        topic: holidays-worker-get
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidayWorkerJacksonDeserializer
      worker-register-route:
        connector: smallrye-kafka
        topic: worker-register-route
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
      worker-update-password-route:
        connector: smallrye-kafka
        topic: worker-update-password-route
        value:
          deserializer: com.kronostools.timehammer.common.messages.updatePassword.deserializers.WorkerUpdatePasswordRequestJacksonDeserializer
      status-worker-get:
        connector: smallrye-kafka
        topic: status-worker-get
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.CheckWorkersStatusWorkerJacksonDeserializer
    outgoing:
      comunytek-worker-holidays:
        connector: smallrye-kafka
        topic: comunytek-worker-holidays
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      comunytek-worker-register:
        connector: smallrye-kafka
        topic: comunytek-worker-register
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      comunytek-worker-update-password:
        connector: smallrye-kafka
        topic: comunytek-worker-update-password
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      comunytek-worker-status:
        connector: smallrye-kafka
        topic: comunytek-worker-status
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer