mp:
  messaging:
    incoming:
      holidays-worker-get:
        connector: smallrye-kafka
        topic: holidays-worker-get
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidaysWorkerDeserializer
    outgoing:
      comunytek-worker-holidays:
        connector: smallrye-kafka
        topic: comunytek-worker-holidays
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer