mp:
  messaging:
    incoming:
      holidays-worker-get:
        connector: smallrye-kafka
        topic: holidays-worker-get
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.UpdateWorkersHolidaysWorkerDeserializer
      worker-register-route:
        connector: smallrye-kafka
        topic: worker-register-route
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
    outgoing:
      comunytek-worker-holidays:
        connector: smallrye-kafka
        topic: comunytek-worker-holidays
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      comunytek-worker-register:
        connector: smallrye-kafka
        topic: comunytek-worker-register
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer