mp:
  messaging:
    incoming:
      command-process:
        connector: smallrye-kafka
        topic: command-process
        value:
          deserializer: com.kronostools.timehammer.common.messages.telegramchatbot.deserializers.TelegramChatbotInputMessageJacksonDeserializer
      worker-register-init:
        connector: smallrye-kafka
        topic: worker-register-init
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
      worker-update-password-init:
        connector: smallrye-kafka
        topic: worker-update-password-init
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerUpdatePasswordRequestJacksonDeserializer
    outgoing:
      notification-telegram:
        connector: smallrye-kafka
        topic: notification-telegram
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-register-validate:
        connector: smallrye-kafka
        topic: worker-register-validate
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-update-password-validate:
        connector: smallrye-kafka
        topic: worker-update-password-validate
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

timehammer:
  domain:
    base-url: https://timehammer.kronostools.com
  chatbot:
    registration-request-cache:
      expiration:
        qty: 10
        unit: MINUTES
    update-password-request-cache:
      expiration:
        qty: 10
        unit: MINUTES

"%localdemo":
  timehammer:
    domain:
      base-url: http://192.168.86.168:9000