mp:
  messaging:
    incoming:
      batch-schedule-summary:
        connector: smallrye-kafka
        topic: batch-schedule-summary
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.BatchScheduleSummaryMessageJacksonDeserializer
      schedule-summary:
        connector: smallrye-kafka
        topic: schedule-summary
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.ScheduleSummaryMessageJacksonDeserializer
      timemachine-stream:
        connector: smallrye-kafka
        topic: timemachine
        value:
          deserializer: com.kronostools.timehammer.common.messages.timemachine.deserializers.TimeMachineEventJacksonDeserializer
      worker-register-notify:
        connector: smallrye-kafka
        topic: worker-register-notify
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
      worker-update-password-notify:
        connector: smallrye-kafka
        topic: worker-update-password-notify
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerUpdatePasswordRequestJacksonDeserializer
      catalog-response:
        connector: smallrye-kafka
        topic: catalog-response
        value:
          deserializer: com.kronostools.timehammer.common.messages.catalog.deserializers.CatalogMessageJacksonDeserializer
    outgoing:
      timemachine-out:
        connector: smallrye-kafka
        topic: timemachine
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-register-init:
        connector: smallrye-kafka
        topic: worker-register-init
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-update-password-init:
        connector: smallrye-kafka
        topic: worker-update-password-init
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      catalog-request:
        connector: smallrye-kafka
        topic: catalog-request
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      schedule-update-status:
        connector: smallrye-kafka
        topic: schedule-update-status
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      schedule-update-holidays:
        connector: smallrye-kafka
        topic: schedule-update-holidays
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      schedule-clean-holidays:
        connector: smallrye-kafka
        topic: schedule-clean-holidays
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer