mp:
  messaging:
    incoming:
      batch-schedule-summary:
        connector: smallrye-kafka
        topic: batch-schedule-summary
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.ScheduleSummaryMessageJacksonDeserializer
      schedule-summary:
        connector: smallrye-kafka
        topic: schedule-summary
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.BatchScheduleSummaryMessageJacksonDeserializer
      timemachine-stream:
        connector: smallrye-kafka
        topic: timemachine
        value:
          deserializer: com.kronostools.timehammer.common.messages.timemachine.deserializers.TimeMachineEventJacksonDeserializer
      worker-register-notify-in:
        connector: smallrye-kafka
        topic: worker-register-notify
        value:
          deserializer: com.kronostools.timehammer.common.messages.registration.deserializers.WorkerRegistrationRequestJacksonDeserializer
      catalog-response:
        connector: smallrye-kafka
        topic: catalog-response
        value:
          deserializer: com.kronostools.timehammer.common.messages.catalog.deserializers.CatalogMessageJacksonDeserializer
    outgoing:
      timemachine-out:
        connector: smallrye-kafka
        topic: timemachine
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-worker-update:
        connector: smallrye-kafka
        topic: holidays-worker-update
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      worker-register-init:
        connector: smallrye-kafka
        topic: worker-register-init
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      catalog-request:
        connector: smallrye-kafka
        topic: catalog-request
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer