mp:
  messaging:
    incoming:
      schedule-summary:
        connector: smallrye-kafka
        topic: schedule-summary
        value:
          deserializer: com.kronostools.timehammer.common.messages.schedules.deserializers.BatchScheduleSummaryMessageJacksonDeserializer
      timemachine-stream:
        connector: smallrye-kafka
        topic: timemachine
        value:
          deserializer: com.kronostools.timehammer.common.messages.timemachine.deserializers.TimeMachineEventJacksonDeserializer
    outgoing:
      timemachine-out:
        connector: smallrye-kafka
        topic: timemachine
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-worker-update:
        connector: smallrye-kafka
        topic: holidays-worker-update
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer