mp:
  messaging:
    outgoing:
      timemachine-out:
        connector: smallrye-kafka
        topic: timemachine
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      holidays-worker-update:
        connector: smallrye-kafka
        topic: holidays-worker-update
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer